export const exercises = [
  { name: 'Back Squat' },
  { name: 'Barbell Row' },
  { name: 'Bench Press' },
  { name: 'Chin-Up' },
  { name: 'Deadlift' },
  { name: 'Decline Bench Press' },
  { name: 'Dips' },
  { name: 'Floor Press' },
  { name: 'Front Squat' },
  { name: 'Good Morning' },
  { name: 'Handstand Push-Up' },
  { name: 'Incline Bench Press' },
  { name: 'JM Press' },
  { name: 'L-Sit' },
  { name: 'Muscle-Up' },
  { name: 'Overhead Press' },
  { name: 'Pistol Squat' },
  { name: 'Pull-Up' },
  { name: 'Push-Up' },
  { name: 'Sissy Squat' },
] satisfies { name: string }[];
